### PR TITLE
added conrtollers folder, index.js, and style.css

### PR DESCRIPTION
**Pull request by ChotanSharma**

### CODE REVIEW

**Review by ChotanSharma — COMMENTED** [review]
Looking good.

**Review by hjohnsick — COMMENTED** [review]
Hi Chotan, we will wait until everything is done to merge into main.  So our workflow will be we create a new branch off of develop for the  feature we are working on.  Once we are done with that feature we will submit a pull request to merge that feature into develop.  Then at the end of the project once all feature branches have been merged into develop we will merge develop at once into main.

**Comment by hjohnsick** [comment]
Closing this pull request as it is not needed at this time.  We will submit a pull request from develop into main once all of the tasks/features are completed.  This will keep everyones local branches in sync.

**Comment by ChotanSharma** [comment]
Hi Heather,
Thank you for the reply. I got it. I was just trying to understand the merge from my site. 
    On Tuesday, March 8, 2022, 11:00:06 AM EST, Heather ***@***.***> wrote:  
 
 


@hjohnsick commented on this pull request.

Hi Chotan, we will wait until everything is done to merge into main. So our workflow will be we create a new branch off of develop for the feature we are working on. Once we are done with that feature we will submit a pull request to merge that feature into develop. Then at the end of the project once all feature branches have been merged into develop we will merge develop at once into main.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Pull request closed without merging**
